In [1]:
import os
import kagglehub
import shutil
import pandas as pd
print("Current directory:", os.getcwd())

Current directory: c:\Users\jsull\Python Projects\MarchMadness

In [2]:
if "DEV _ March Madness.csv" not in os.listdir():    
    # Specify the desired download location
    download_path = os.getcwd() 

    # Download latest version to the specified path
    path = kagglehub.dataset_download("jonathanpilafas/2024-march-madness-statistical-analysis")

    print("Path to dataset files:", path)

    # Move the downloaded files from path to download_path
    for filename in os.listdir(path):
        shutil.move(os.path.join(path, filename), download_path)

    print("Files moved to:", download_path)
else:
    print("Files already downloaded")

Files already downloaded

In [3]:
file_contents = {}
for file in os.listdir():
    if file.endswith(".csv"):
        df = pd.read_csv(file, nrows=0)
        header = list(df.columns)
        file_contents[file] = header

file_contents

{'DEV _ March Madness.csv': ['Season',
  'Short Conference Name',
  'Adjusted Temo',
  'Adjusted Tempo Rank',
  'Raw Tempo',
  'Raw Tempo Rank',
  'Adjusted Offensive Efficiency',
  'Adjusted Offensive Efficiency Rank',
  'Raw Offensive Efficiency',
  'Raw Offensive Efficiency Rank',
  'Adjusted Defensive Efficiency',
  'Adjusted Defensive Efficiency Rank',
  'Raw Defensive Efficiency',
  'Raw Defensive Efficiency Rank',
  'Avg Possession Length (Offense)',
  'Avg Possession Length (Offense) Rank',
  'Avg Possession Length (Defense)',
  'Avg Possession Length (Defense) Rank',
  'eFGPct',
  'RankeFGPct',
  'TOPct',
  'RankTOPct',
  'ORPct',
  'RankORPct',
  'FTRate',
  'RankFTRate',
  'OffFT',
  'RankOffFT',
  'Off2PtFG',
  'RankOff2PtFG',
  'Off3PtFG',
  'RankOff3PtFG',
  'DefFT',
  'RankDefFT',
  'Def2PtFG',
  'RankDef2PtFG',
  'Def3PtFG',
  'RankDef3PtFG',
  'Tempo',
  'RankTempo',
  'AdjTempo',
  'RankAdjTempo',
  'OE',
  'RankOE',
  'AdjOE',
  'RankAdjOE',
  'DE',
  'RankDE',
  'AdjDE',
  'RankAdjDE',
  'AdjEM',
  'RankAdjEM',
  'FG2Pct',
  'RankFG2Pct',
  'FG3Pct',
  'RankFG3Pct',
  'FTPct',
  'RankFTPct',
  'BlockPct',
  'RankBlockPct',
  'OppFG2Pct',
  'RankOppFG2Pct',
  'OppFG3Pct',
  'RankOppFG3Pct',
  'OppFTPct',
  'RankOppFTPct',
  'OppBlockPct',
  'RankOppBlockPct',
  'FG3Rate',
  'RankFG3Rate',
  'OppFG3Rate',
  'RankOppFG3Rate',
  'ARate',
  'RankARate',
  'OppARate',
  'RankOppARate',
  'StlRate',
  'RankStlRate',
  'OppStlRate',
  'RankOppStlRate',
  'DFP',
  'NSTRate',
  'RankNSTRate',
  'OppNSTRate',
  'RankOppNSTRate',
  'AvgHeight',
  'RankAvgHeight',
  'CenterHeight',
  'RankCenterHeight',
  'PFHeight',
  'RankPFHeight',
  'SFHeight',
  'RankSFHeight',
  'SGHeight',
  'RankSGHeight',
  'PGHeight',
  'RankPGHeight',
  'EffectiveHeight',
  'RankEffectiveHeight',
  'Experience',
  'RankExperience',
  'Bench',
  'BenchRank',
  'CenterPts',
  'RankCenterPts',
  'PFPts',
  'RankPFPts',
  'SFPts',
  'RankSFPts',
  'SGPts',
  'RankSGPts',
  'PGPts',
  'RankPGPts',
  'CenterOR',
  'RankCenterOR',
  'PFOR',
  'RankPFOR',
  'SFOR',
  'RankSFOR',
  'SGOR',
  'RankSGOR',
  'PGOR',
  'RankPGOR',
  'CenterDR',
  'RankCenterDR',
  'PFDR',
  'RankPFDR',
  'SFDR',
  'RankSFDR',
  'SGDR',
  'RankSGDR',
  'PGDR',
  'RankPGDR',
  'Net Rating',
  'Net Rating Rank',
  'Mapped Conference Name',
  'Mapped ESPN Team Name',
  'Current Coach',
  'Full Team Name',
  'Since',
  'Active Coaching Length',
  'Active Coaching Length Index',
  'Seed',
  'Region',
  'Correct Team Name?',
  'Post-Season Tournament',
  'Post-Season Tournament Sorting Index'],
 'INT _ KenPom _ Defense.csv': ['Season',
  'TeamName',
  'eFGPct',
  'RankeFGPct',
  'TOPct',
  'RankTOPct',
  'ORPct',
  'RankORPct',
  'FTRate',
  'RankFTRate'],
 'INT _ KenPom _ Efficiency.csv': ['Season',
  'Team',
  'Conference',
  'Adjusted Temo',
  'Adjusted Tempo Rank',
  'Raw Tempo',
  'Raw Tempo Rank',
  'Adjusted Offensive Efficiency',
  'Adjusted Offensive Efficiency Rank',
  'Raw Offensive Efficiency',
  'Raw Offensive Efficiency Rank',
  'Adjusted Defensive Efficiency',
  'Adjusted Defensive Efficiency Rank',
  'Raw Defensive Efficiency',
  'Raw Defensive Efficiency Rank',
  'Avg Possession Length (Offense)',
  'Avg Possession Length (Offense) Rank',
  'Avg Possession Length (Defense)',
  'Avg Possession Length (Defense) Rank'],
 'INT _ KenPom _ Height.csv': ['Season',
  'TeamName',
  'AvgHeight',
  'RankAvgHeight',
  'CenterHeight',
  'RankCenterHeight',
  'PFHeight',
  'RankPFHeight',
  'SFHeight',
  'RankSFHeight',
  'SGHeight',
  'RankSGHeight',
  'PGHeight',
  'RankPGHeight',
  'EffectiveHeight',
  'RankEffectiveHeight',
  'Experience',
  'RankExperience',
  'Bench',
  'BenchRank',
  'CenterPts',
  'RankCenterPts',
  'PFPts',
  'RankPFPts',
  'SFPts',
  'RankSFPts',
  'SGPts',
  'RankSGPts',
  'PGPts',
  'RankPGPts',
  'CenterOR',
  'RankCenterOR',
  'PFOR',
  'RankPFOR',
  'SFOR',
  'RankSFOR',
  'SGOR',
  'RankSGOR',
  'PGOR',
  'RankPGOR',
  'CenterDR',
  'RankCenterDR',
  'PFDR',
  'RankPFDR',
  'SFDR',
  'RankSFDR',
  'SGDR',
  'RankSGDR',
  'PGDR',
  'RankPGDR'],
 'INT _ KenPom _ Miscellaneous Team Stats.csv': ['Season',
  'TeamName',
  'FG2Pct',
  'RankFG2Pct',
  'FG3Pct',
  'RankFG3Pct',
  'FTPct',
  'RankFTPct',
  'BlockPct',
  'RankBlockPct',
  'OppFG2Pct',
  'RankOppFG2Pct',
  'OppFG3Pct',
  'RankOppFG3Pct',
  'OppFTPct',
  'RankOppFTPct',
  'OppBlockPct',
  'RankOppBlockPct',
  'FG3Rate',
  'RankFG3Rate',
  'OppFG3Rate',
  'RankOppFG3Rate',
  'ARate',
  'RankARate',
  'OppARate',
  'RankOppARate',
  'StlRate',
  'RankStlRate',
  'OppStlRate',
  'RankOppStlRate',
  'DFP',
  'NSTRate',
  'RankNSTRate',
  'OppNSTRate',
  'RankOppNSTRate'],
 'INT _ KenPom _ Offense.csv': ['Season',
  'TeamName',
  'eFGPct',
  'RankeFGPct',
  'TOPct',
  'RankTOPct',
  'ORPct',
  'RankORPct',
  'FTRate',
  'RankFTRate'],
 'INT _ KenPom _ Point Distribution.csv': ['Season',
  'TeamName',
  'OffFT',
  'RankOffFT',
  'Off2PtFG',
  'RankOff2PtFG',
  'Off3PtFG',
  'RankOff3PtFG',
  'DefFT',
  'RankDefFT',
  'Def2PtFG',
  'RankDef2PtFG',
  'Def3PtFG',
  'RankDef3PtFG'],
 'INT _ KenPom _ Summary.csv': ['Season',
  'TeamName',
  'Tempo',
  'RankTempo',
  'AdjTempo',
  'RankAdjTempo',
  'OE',
  'RankOE',
  'AdjOE',
  'RankAdjOE',
  'DE',
  'RankDE',
  'AdjDE',
  'RankAdjDE',
  'AdjEM',
  'RankAdjEM'],
 'REF _ 2024 Post-Season Tournament Locations.csv': ['Sub-Regions',
  'Sweet 16 Regions',
  'Final Four Regions',
  'Sub-Regions Stadium Name',
  'Sub-Regions ZIP Code',
  'Sweet 16 Regions Stadium Name',
  'Sweet 16 Regions ZIP Code',
  'Final Four Regions Stadium Name',
  'Final Four Regions ZIP Code'],
 'REF _ 2024 Post-Season Tournament Teams.csv': ['Team Name',
  'Seed',
  'Region',
  'Correct Team Name?',
  'Post-Season Tournament',
  'Post-Season Tournament Sorting Index'],
 'REF _ Current NCAAM Coaches.csv': ['Current Coach',
  'Team',
  'Since',
  'Join Team']}

In [6]:
tourney_to_season = {
    "Abilene Chr": "Abilene Christian",
    "SUNY Albany": "Albany",
    "American Univ": "American",
    'Ark Little Rock': "Arkansas Little Rock",
    'Ark Pine Bluff': "Arkansas Pine Bluff",
    'Bethune-Cookman': "Bethune Cookman",
    'Birmingham So': 'Birmingham Southern',
    'Boston Univ': 'Boston University',
    'Brooklyn': 'LIU Brooklyn',
    'C Michigan': 'Central Michigan',
    'Cent Arkansas': 'Central Arkansas',
    'Central Conn': 'Central Connecticut',
    'Charleston So': 'Charleston Southern',
    'Citadel': 'The Citadel',
    'Coastal Car': 'Coastal Carolina',
    'Col Charleston': 'Charleston',
    'CS Bakersfield': 'Cal St. Bakersfield',
    'CS Fullerton': 'Cal St. Fullerton',
    'CS Northridge': 'Cal St. Northridge',
    'CS Sacramento': 'Sacramento St.',
    'E Illinois': 'Eastern Illinois',
    'E Kentucky': 'Eastern Kentucky',
    'E Michigan': 'Eastern Michigan',
    'E Washington': 'Eastern Washington',
    'ETSU': 'East Tennessee St.',
    'F Dickinson': 'Fairleigh Dickinson',
    'FL Atlantic': 'Florida Atlantic',
    'FGCU': 'Florida Gulf Coast',
    'Florida Intl': 'FIU',
    'G Washington': 'George Washington',
    'Ga Southern': 'Georgia Southern',
    'Grambling': 'Grambling St.',
    'Houston Chr': 'Houston Christian',
    'IL Chicago': 'Illinois Chicago',
    'PFW': 'Purdue Fort Wayne',
    'Kennesaw': 'Kennesaw St.',
    'Loy Marymount': 'Loyola Marymount',
    'Loyola-Chicago': 'Loyola Chicago',
    'MA Lowell': 'UMass Lowell',
    'MD E Shore': 'Maryland Eastern Shore',
    'Missouri KC': 'UMKC',
    'Monmouth NJ': 'Monmouth',
    'MS Valley St.': 'Mississippi Valley St.',
    "Mt St. Mary's": "Mount St. Mary's",
    'MTSU': 'Middle Tennessee',
    'N Colorado': 'Northern Colorado',
    'N Dakota St.': 'North Dakota St.',
    'N Illinois': 'Northern Illinois',
    'N Kentucky': 'Northern Kentucky',
    'NC A&T': 'North Carolina A&T',
    'NC Central': 'North Carolina Central',
    'NC St.ate': 'NC State',
    'NE Omaha': 'Nebraska Omaha',
    'Prairie View': 'Prairie View A&M',
    'S Carolina St.': 'South Carolina St.',
    'S Dakota St.': 'South Dakota St.',
    'S Illinois': 'Southern Illinois',
    'SC Upstate': 'USC Upstate',
    'SE Louisiana': 'Southeastern Louisiana',
    'SE Missouri St.': 'Southeast Missouri St.',
    'SF Austin': 'Stephen F. Austin',
    'Southern Univ': 'Southern',
    'St Bonaventure': 'St. Bonaventure',
    'St Francis NY': 'St. Francis NY',
    'St Francis PA': 'St. Francis PA',
    "St John's": "St. John's",
    "St Joseph's PA": "Saint Joseph's",
    'St Louis': 'Saint Louis',
    "St Mary's CA": "Saint Mary's",
    "St Peter's": "Saint Peter's",
    'TAM C. Christi': 'Texas A&M Corpus Chris',
    'TN Martin': 'Tennessee Martin',
    'UTRGV': 'UT Rio Grande Valley',
    'TX Southern': 'Texas Southern',
    'ULM': 'Louisiana Monroe',
    'UT San Antonio': 'UTSA',
    'W Carolina': 'Western Carolina',
    'W Illinois': 'Western Illinois',
    'WKU': 'Western Kentucky',
    'W Michigan': 'Western Michigan',
    'W Salem St.': 'Winston Salem St.',
    'WI Green Bay': 'Green Bay',
    'WI Milwaukee': 'Milwaukee',
    'St Thomas MN': 'St. Thomas',
    'Queens NC': 'Queens'
}

In [7]:
tourney_teams = pd.read_csv("march_games/MTeams.csv")
tourney_teams['TeamName'] = tourney_teams['TeamName'].str.replace(' St', ' St.')
tourney_teams['TeamName'] = tourney_teams['TeamName'].map(lambda x: tourney_to_season.get(x, x))
tourney_teams.head()

   TeamID           TeamName  FirstD1Season  LastD1Season
0    1101  Abilene Christian           2014          2025
1    1102          Air Force           1985          2025
2    1103              Akron           1985          2025
3    1104            Alabama           1985          2025
4    1105        Alabama A&M           2000          2025

In [8]:
season_stat_teams = pd.read_csv('INT _ KenPom _ Summary.csv')[["Season", "TeamName"]]
season_stat_teams['TeamName'] = season_stat_teams['TeamName'].str.replace('Wisconsin Green Bay', 'Green Bay')
season_stat_teams['TeamName'] = season_stat_teams['TeamName'].str.replace('Wisconsin Milwaukee', 'Milwaukee')
# season_stat_teams['TeamName'] = season_stat_teams['TeamName'].str.replace(" St", " St.")

In [9]:
# # Find team names in season_stat_teams that are not in tourney_teams
# season_only_teams = season_stat_teams[['TeamName']][~season_stat_teams['TeamName'].isin(tourney_teams['TeamName'])]

# Find team names in tourney_teams that are not in season_stat_teams
tourney_only_teams = tourney_teams[['TeamName']][~tourney_teams['TeamName'].isin(season_stat_teams['TeamName'])]

print(list(tourney_only_teams['TeamName']))

['Alliant Intl', 'Armstrong St.', 'Augusta', 'Hardin-Simmons', 'NE Illinois', 'Northwestern LA', 'Okla City', 'Utica', 'W Texas A&M']

In [10]:
print(len(list(tourney_only_teams['TeamName'])))

9

In [11]:
def lookup_season_teams(phrase):
    return season_stat_teams[season_stat_teams['TeamName'].str.contains(phrase)].sort_values('Season')

In [12]:
lookup_season_teams("Corpus") 
# not in data: Armstrong St., Alliant Intl, Augusta, Hardin-Simmons, NE Illinois, Northwestern LA, Okla City, Utica, W Texas A&M
# Note that UMKC is now Kansas City for 2025
# Wisconsin Green Bay is Green Bay starting 2001 -- FIXED
# Wisconsin Milwaukee is Milwaukee starting 2001 -- FIXED

      Season                TeamName
8949    2001  Texas A&M Corpus Chris
9040    2002  Texas A&M Corpus Chris
9212    2003  Texas A&M Corpus Chris
7943    2004  Texas A&M Corpus Chris
6980    2005  Texas A&M Corpus Chris
3860    2006  Texas A&M Corpus Chris
1663    2007  Texas A&M Corpus Chris
8803    2008  Texas A&M Corpus Chris
6490    2009  Texas A&M Corpus Chris
4644    2010  Texas A&M Corpus Chris
3332    2011  Texas A&M Corpus Chris
2297    2012  Texas A&M Corpus Chris
7524    2013  Texas A&M Corpus Chris
9131    2014  Texas A&M Corpus Chris
5284    2015  Texas A&M Corpus Chris
7888    2016  Texas A&M Corpus Chris
2976    2017  Texas A&M Corpus Chris
4242    2018  Texas A&M Corpus Chris
8662    2019  Texas A&M Corpus Chris
304     2020  Texas A&M Corpus Chris
5841    2021  Texas A&M Corpus Chris
6148    2022  Texas A&M Corpus Chris
665     2023  Texas A&M Corpus Chris
6661    2024  Texas A&M Corpus Chris
7279    2025  Texas A&M Corpus Chris

In [13]:
season_results = pd.read_csv("march_games/MRegularSeasonCompactResults.csv")
season_wins = season_results.groupby(['Season', 'WTeamID']).size().reset_index(name='Wins')
season_losses = season_results.groupby(['Season', 'LTeamID']).size().reset_index(name='Losses')
season_record = season_wins.merge(season_losses, left_on=['Season', 'WTeamID'], right_on=['Season', 'LTeamID'], how='outer')
season_record['Record'] = season_record['Wins'].fillna(0) / (season_record['Wins'].fillna(0) + season_record['Losses'].fillna(0))
season_record = season_record.merge(tourney_teams[['TeamID', 'TeamName']], left_on='WTeamID', right_on='TeamID')
season_record.drop(columns=['WTeamID', 'LTeamID'], inplace=True)
season_record = season_record[['Season', 'TeamName', 'TeamID', 'Wins', 'Losses', 'Record']]
season_record.head()

   Season   TeamName  TeamID  Wins  Losses    Record
0    1985  Air Force    1102   5.0    19.0  0.208333
1    1986  Air Force    1102   6.0    19.0  0.240000
2    1987  Air Force    1102   8.0    15.0  0.347826
3    1988  Air Force    1102   7.0    17.0  0.291667
4    1989  Air Force    1102  10.0    14.0  0.416667

In [15]:
tourney_games = pd.read_csv("march_games/MNCAATourneyCompactResults.csv")
tourney_games = tourney_games[tourney_games['Season'] >= 2002]
seeds = pd.read_csv("march_games/MNCAATourneySeeds.csv")
tourney_games = tourney_games.merge(tourney_teams[['TeamID', 'TeamName']], left_on='WTeamID', right_on='TeamID').merge(seeds, left_on=['Season', 'WTeamID'], right_on=['Season', 'TeamID'])
tourney_games.drop(columns=['TeamID_x', 'TeamID_y', 'WLoc', 'NumOT'], inplace=True)
tourney_games.rename(columns={'TeamName': 'WTeamName', 'Seed': 'WSeed'}, inplace=True)
tourney_games['WSeed'] = tourney_games['WSeed'].str.extract('(\d+)').astype(int)
tourney_games = tourney_games.merge(season_record, left_on=['Season', 'WTeamID'], right_on=['Season', 'TeamID'], how='left').drop(columns=['Wins', 'Losses', 'TeamID', 'TeamName'])
tourney_games.rename(columns={'Record': 'WRecord'}, inplace=True)
tourney_games = tourney_games.merge(tourney_teams[['TeamID', 'TeamName']], left_on='LTeamID', right_on='TeamID').merge(seeds, left_on=['Season', 'LTeamID'], right_on=['Season', 'TeamID'])
tourney_games.drop(columns=['TeamID_x', 'TeamID_y'], inplace=True)
tourney_games.rename(columns={'TeamName': 'LTeamName', 'Seed': 'LSeed'}, inplace=True)
tourney_games['LSeed'] = tourney_games['LSeed'].str.extract('(\d+)').astype(int)
tourney_games = tourney_games.merge(season_record, left_on=['Season', 'LTeamID'], right_on=['Season', 'TeamID'], how='left').drop(columns=['Wins', 'Losses', 'TeamID', 'TeamName'])
tourney_games.rename(columns={'Record': 'LRecord'}, inplace=True)
tourney_games

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WTeamName,WSeed,WRecord,LTeamName,LSeed,LRecord
0,2002,134,1373,81,1108,77,Siena,16,0.470588,Alcorn St.,16,0.689655
1,2008,137,1373,83,1435,62,Siena,13,0.687500,Vanderbilt,4,0.787879
2,2004,143,1163,73,1435,53,Connecticut,2,0.818182,Vanderbilt,6,0.700000
3,2012,138,1458,60,1435,57,Wisconsin,4,0.727273,Vanderbilt,5,0.705882
4,2016,134,1455,70,1435,50,Wichita St.,11,0.741935,Vanderbilt,11,0.593750
...,...,...,...,...,...,...,...,...,...,...,...,...
1441,2021,136,1313,54,1111,53,Norfolk St.,16,0.666667,Appalachian St.,16,0.541667
1442,2015,135,1352,81,1316,77,Robert Morris,16,0.575758,North Florida,16,0.645161
1443,2019,134,1192,82,1341,76,Fairleigh Dickinson,16,0.580645,Prairie View A&M,16,0.636364
1444,2022,135,1460,93,1136,82,Wright St.,16,0.606061,Bryant,16,0.700000
1445,2023,134,1394,75,1369,71,Texas A&M Corpus Chris,16,0.655172,Southeast Missouri St.,16,0.515152